# Generated by Django 4.0.6 on 2022-08-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0019_alter_user_status'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventtypes', verbose_name='Тип мероприятия'),
        ),
        migrations.AddField(
            model_name='eventtypes',
            name='for_status',
            field=models.ManyToManyField(to='tgbot.status'),
        ),
    ]
