# Generated by Django 4.0.6 on 2022-08-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0019_alter_user_status'),
        ('events', '0002_events_type_eventtypes_for_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypes',
            name='for_status',
            field=models.ManyToManyField(blank=True, null=True, to='tgbot.status', verbose_name='Для пользователей со статусом'),
        ),
    ]
