# Generated by Django 4.0.6 on 2022-08-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventtypes_for_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventtypes', verbose_name='Тип мероприятия'),
        ),
    ]
