# Generated by Django 4.0.6 on 2022-08-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0020_remove_status_stat_id_status_code_and_more'),
        ('events', '0008_remove_eventtypes_for_status_events_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='transaction',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные транзакции оплаты'),
        ),
        migrations.CreateModel(
            name='EventRequests',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер заявки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Стоимость мероприятия')),
                ('payed', models.BooleanField(default=False, verbose_name='Оплачена')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='Оценка мероприятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events', verbose_name='Мероприятие')),
                ('for_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.status', verbose_name='Для статуса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на мероприятие',
                'verbose_name_plural': 'Заявки на мероприятия',
                'ordering': ['event', 'user'],
            },
        ),
    ]
