# Generated by Django 4.0.6 on 2022-08-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_events_transaction_eventrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='transaction',
        ),
        migrations.AddField(
            model_name='eventrequests',
            name='transaction',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные транзакции оплаты'),
        ),
    ]
