# Generated by Django 4.0.6 on 2022-08-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_events_transaction_eventrequests_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequests',
            name='transaction',
        ),
    ]
