# Generated by Django 4.0.6 on 2022-08-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('events', '0011_remove_eventrequests_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequests',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payments', verbose_name='Документ платежа'),
        ),
    ]
