# Generated by Django 4.0.6 on 2022-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventrequests_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequests',
            name='qr_code_sended',
            field=models.BooleanField(default=False, verbose_name='QR код подтверждения отослан'),
        ),
    ]
