# Generated by Django 4.0.6 on 2022-08-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventrequests_qr_code_sended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='events',
            name='invite_file_id',
        ),
    ]
