# Generated by Django 4.0.6 on 2022-08-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0028_user_segment_user_turnover'),
        ('events', '0016_remove_events_invite_remove_events_invite_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст анонса')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events', verbose_name='Мероприятие')),
                ('sending_groups', models.ManyToManyField(to='tgbot.tggroups', verbose_name='Группы для рассылки')),
            ],
            options={
                'verbose_name': 'Анонс мероприятия',
                'verbose_name_plural': 'Анонсы мероприятий',
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='AnonsesDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons_date', models.DateTimeField(verbose_name='Дата отправки')),
                ('sended', models.BooleanField(default=False, verbose_name='Отослан')),
                ('anons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.anonses', verbose_name='Анонс')),
            ],
            options={
                'verbose_name': 'Дата отправки анонса',
                'verbose_name_plural': 'Даты отправки анонсов',
                'ordering': ['anons', 'anons_date'],
            },
        ),
    ]
