# Generated by Django 4.0.6 on 2022-08-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_anonses_anonsesdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonses',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='events', verbose_name='Фото/Видео'),
        ),
        migrations.AddField(
            model_name='anonses',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id'),
        ),
        migrations.AlterField(
            model_name='anonsesdates',
            name='anons_date',
            field=models.DateField(verbose_name='Дата отправки'),
        ),
    ]
