# Generated by Django 4.0.6 on 2022-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0030_offers_image_id'),
        ('events', '0018_anonses_file_anonses_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonses',
            name='sending_groups',
            field=models.ManyToManyField(blank=True, null=True, to='tgbot.tggroups', verbose_name='Группы для рассылки'),
        ),
    ]
