# Generated by Django 4.0.6 on 2022-08-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0029_tggroups_file_tggroups_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('full_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Полное наименование')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegramm ID')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предложения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание предложения')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('file', models.FileField(blank=True, null=True, upload_to='advert', verbose_name='Фото/Видео')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id')),
                ('pertner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.partnes', verbose_name='Партнер')),
                ('sending_groups', models.ManyToManyField(to='tgbot.tggroups', verbose_name='Группы для рассылки')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffersDiscounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(verbose_name='Скидка, %')),
                ('for_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.status', verbose_name='Для статуса')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.specialoffers', verbose_name='Спец. предложение')),
            ],
            options={
                'verbose_name': 'Скидка для предложения',
                'verbose_name_plural': 'Скидки для предложения',
                'ordering': ['offer'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffersDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField(verbose_name='Дата отправки')),
                ('sended', models.BooleanField(default=False, verbose_name='Отослан')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.specialoffers', verbose_name='Спец. предложение')),
            ],
            options={
                'verbose_name': 'Дата отправки предложения',
                'verbose_name_plural': 'Даты отправки предложений',
                'ordering': ['offer', 'offer_date'],
            },
        ),
        migrations.CreateModel(
            name='SOUserRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(verbose_name='Скидка, %')),
                ('sended_to_partner', models.BooleanField(default=False, verbose_name='Отослан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('discount_code', models.CharField(max_length=20, verbose_name='Код скидки')),
                ('for_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.status', verbose_name='Для статуса')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.specialoffers', verbose_name='Спец. предложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на предложение',
                'verbose_name_plural': 'Запросы на предложения',
                'ordering': ['created_at', 'offer'],
            },
        ),
    ]
