# Generated by Django 4.0.6 on 2022-08-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialoffers',
            options={'verbose_name': 'Специальное предложение', 'verbose_name_plural': 'Специальные предложения'},
        ),
        migrations.RenameField(
            model_name='specialoffers',
            old_name='pertner',
            new_name='partner',
        ),
    ]
