# Generated by Django 4.0.6 on 2022-09-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0031_alter_user_date_of_birth'),
        ('advert', '0002_alter_specialoffers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffers',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AddField(
            model_name='specialoffers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='specialoffers',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.partnes', verbose_name='Партнер'),
        ),
    ]
