# Generated by Django 4.0.6 on 2022-11-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0032_remove_user_updated_at_user_registered_and_more'),
        ('advert', '0003_specialoffers_confirmed_specialoffers_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffers',
            name='sending_groups',
            field=models.ManyToManyField(blank=True, to='tgbot.tggroups', verbose_name='Группы для рассылки'),
        ),
    ]
