# Generated by Django 4.0.6 on 2022-08-25 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0029_tggroups_file_tggroups_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код пакета')),
                ('name', models.CharField(max_length=150, verbose_name='Пакет участия')),
            ],
            options={
                'verbose_name': 'Пакет участия',
                'verbose_name_plural': 'Пакеты участия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageDescrForStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('for_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.status', verbose_name='Для статуса')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.clubpackages', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Описание пакета участия',
                'verbose_name_plural': 'Описание пакетов участия',
                'ordering': ['package', 'for_status'],
            },
        ),
    ]
