# Docker-команда FROM указывает базовый образ контейнера
# Наш базовый образ - это Linux с предустановленным python-3.7
FROM python:3.9-slim
# Скопируем файл с зависимостями в контейнер
#WORKDIR /app#

COPY requirements.txt .
# Установим зависимости внутри контейнера
RUN pip3 install -r requirements.txt
# Скопируем остальные файлы в контейнер
COPY . .
COPY .env_dep .env
EXPOSE 8001
# запускаем скрипт
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]