version: '3'

volumes:
  production_traefik: {}

services:
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: urbanius_bot_production_traefik
    network_mode: host
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped

  nginx-media:
    image: "nginx:latest"
    # ports:
    #   - "8000:80"
    environment:
      - NGINX_PORT=8000
    volumes:
      - ./media:/usr/share/nginx/html/media:ro
    restart: unless-stopped
    network_mode: host


