# Generated by Django 4.0.6 on 2022-08-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='stat_id',
            field=models.IntegerField(null=True, verbose_name='ИД статуса'),
        ),
        migrations.AddField(
            model_name='tggroups',
            name='chat_id',
            field=models.BigIntegerField(null=True, verbose_name='ИД чата в Телеграм'),
        ),
        migrations.CreateModel(
            name='UsertgGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.tggroups', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Группа пользователя',
                'verbose_name_plural': 'Группы пользователя',
                'ordering': ['user', 'group'],
            },
        ),
    ]
