# Generated by Django 4.0.6 on 2022-08-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_status_stat_id_tggroups_chat_id_usertggroups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='club_groups',
        ),
    ]
