# Generated by Django 4.0.6 on 2022-08-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_branch_config_hobby_jobregions_needs_sport_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Член клуба', 'verbose_name_plural': 'Члены клуба'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_login',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.branch', verbose_name='Отрасль'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='user',
            name='club_groups',
        ),
        migrations.AddField(
            model_name='user',
            name='club_groups',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.tggroups', verbose_name='Клубная группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deep_link',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Забанен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked_bot',
            field=models.BooleanField(default=False, verbose_name='Заблоктрован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_region',
        ),
        migrations.AddField(
            model_name='user',
            name='job_region',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.jobregions', verbose_name='Регион работы'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.status', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телеграм логин'),
        ),
    ]
