# Generated by Django 4.0.6 on 2022-08-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_socialnetsites_alter_socialnets_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcgis',
            name='location',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='jobregions',
            options={'ordering': ['code'], 'verbose_name': 'Регион работы', 'verbose_name_plural': 'Регионы работы'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userreferrers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreferrers_set', to='tgbot.user', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Arcgis',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
