# Generated by Django 4.0.6 on 2022-08-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_user_options_remove_user_telegram_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.branch', verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='club_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.tggroups', verbose_name='Клубная группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.jobregions', verbose_name='Регион работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.status', verbose_name='Статус'),
        ),
    ]
