# Generated by Django 4.0.6 on 2022-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_remove_arcgis_location_delete_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_coffe_on',
            field=models.BooleanField(default=False, verbose_name='Подключено Random coffe'),
        ),
    ]
