# Generated by Django 4.0.6 on 2022-08-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_user_random_coffe_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=255, verbose_name='Наименование параметра')),
                ('param_val', models.TextField(blank=True, null=True, verbose_name='Значение параметра')),
            ],
            options={
                'verbose_name': 'Параметр бота',
                'verbose_name_plural': 'Параметры бота',
                'ordering': ['param_name'],
            },
        ),
        migrations.CreateModel(
            name='MessagesToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('sended_at', models.DateTimeField(verbose_name='Отослано в')),
                ('sended', models.BooleanField(default=False, verbose_name='Отослано')),
                ('file', models.FileField(blank=True, upload_to='messages', verbose_name='Файл')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='tgbot.user', verbose_name='Получатель')),
                ('recommended_friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_friend', to='tgbot.user', verbose_name='Рекомендованный друг по Random coffee')),
            ],
            options={
                'verbose_name': 'Сообщение к отсылке',
                'verbose_name_plural': 'Сообщения к отсылке',
                'ordering': ['created_at'],
            },
        ),
    ]
