# Generated by Django 4.0.6 on 2022-08-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_user_branch_alter_user_club_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='needs',
        ),
        migrations.CreateModel(
            name='UserNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.needs', verbose_name='Потребность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Потребность пользователя',
                'verbose_name_plural': 'Потребности пользователя',
                'ordering': ['user', 'need'],
            },
        ),
    ]
