# Generated by Django 4.0.6 on 2022-08-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_config_messagestosend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userneeds',
            name='need',
        ),
        migrations.RemoveField(
            model_name='userneeds',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='needs',
            field=models.TextField(blank=True, null=True, verbose_name='Потребности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked_bot',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.DeleteModel(
            name='Needs',
        ),
        migrations.DeleteModel(
            name='UserNeeds',
        ),
    ]
