# Generated by Django 4.0.6 on 2022-08-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_remove_userneeds_need_remove_userneeds_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhobby',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='userhobby',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersport',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='usersport',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.TextField(blank=True, null=True, verbose_name='Хобби'),
        ),
        migrations.AddField(
            model_name='user',
            name='sport',
            field=models.TextField(blank=True, null=True, verbose_name='Спорт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_region',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Регион присутствия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Тэги'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='JobRegions',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='UserHobby',
        ),
        migrations.DeleteModel(
            name='UserSport',
        ),
    ]
