# Generated by Django 4.0.6 on 2022-08-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_remove_userhobby_hobby_remove_userhobby_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('file', models.FileField(blank=True, null=True, upload_to='templates', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='messagestosend',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='messagestosend',
            name='sended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отослано в'),
        ),
    ]
