# Generated by Django 4.0.6 on 2022-08-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_usersratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_by_security',
            field=models.BooleanField(default=False, verbose_name='Проверен службой безопасности'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer',
            field=models.TextField(blank=True, null=True, verbose_name='Суть предложения'),
        ),
    ]
