# Generated by Django 4.0.6 on 2022-08-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0015_alter_tggroups_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ИНН'),
        ),
    ]
