# Generated by Django 4.0.6 on 2022-08-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0019_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='stat_id',
        ),
        migrations.AddField(
            model_name='status',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deep_link',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Рекомендательная сылка'),
        ),
    ]
