# Generated by Django 4.0.6 on 2022-08-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0020_remove_status_stat_id_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestosend',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id'),
        ),
    ]
