# Generated by Django 4.0.6 on 2022-08-18 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0023_remove_messagestosend_recommended_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телеграм логин')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('telefon', models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон')),
                ('sur_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата рождения')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='Компания')),
                ('job', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('branch', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отрасль')),
                ('citi', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('job_region', models.CharField(blank=True, max_length=150, null=True, verbose_name='Регион присутствия')),
                ('site', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сайт')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('language_code', models.CharField(blank=True, help_text="Telegram client's lang", max_length=8, null=True)),
                ('deep_link', models.CharField(blank=True, max_length=64, null=True, verbose_name='Рекомендательная сылка')),
                ('registered', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
            ],
            options={
                'verbose_name': 'Новый пользователь',
                'verbose_name_plural': 'Новые пользователи',
            },
        ),
    ]
