# Generated by Django 4.0.6 on 2022-08-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0024_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestosend',
            name='receiver_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
