# Generated by Django 4.0.6 on 2022-08-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0026_alter_messagestosend_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagestosend',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='MessageTemplates',
        ),
        migrations.DeleteModel(
            name='MessagesToSend',
        ),
    ]
