# Generated by Django 4.0.6 on 2022-09-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0029_tggroups_file_tggroups_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='image_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id'),
        ),
    ]
