# Generated by Django 4.0.6 on 2022-11-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0033_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_fotos', verbose_name='Основное фото'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='main_photo_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='id основного фото'),
        ),
    ]
