# Generated by Django 4.0.6 on 2022-11-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0034_newuser_main_photo_newuser_main_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='business_club_member',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Членство в бизнес клубах'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='resident_urbanius_club',
            field=models.BooleanField(default=False, verbose_name='Член клуба URBANIUS CLUB'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_club_member',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Членство в бизнес клубах'),
        ),
        migrations.AddField(
            model_name='user',
            name='resident_urbanius_club',
            field=models.BooleanField(default=False, verbose_name='Член клуба URBANIUS CLUB'),
        ),
    ]
