# Generated by Django 4.0.6 on 2022-11-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0038_alter_newuser_company_turnover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='number_of_employees',
            field=models.CharField(choices=[('under 10 employess', 'До 10 человек'), ('from 10 to 50 employess', 'От 10 до 50 человек'), ('from 50 to 500 employess', 'От 50 человек до 500'), ('more then 500 employess', 'От 500 и более')], default='under 10 employess', max_length=50, verbose_name='Численность сотрудников'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_employees',
            field=models.CharField(choices=[('under 10 employess', 'До 10 человек'), ('from 10 to 50 employess', 'От 10 до 50 человек'), ('from 50 to 500 employess', 'От 50 человек до 500'), ('more then 500 employess', 'От 500 и более')], default='under 10 employess', max_length=50, verbose_name='Численность сотрудников'),
        ),
    ]
