# Generated by Django 4.0.6 on 2022-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0039_newuser_number_of_employees_user_number_of_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование потребности')),
            ],
            options={
                'verbose_name': 'Потребность бизнеса',
                'verbose_name_plural': 'Потребности бизнеса',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='newuser',
            name='business_needs',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tgbot.businessneeds', verbose_name='Потребности бизнеса'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_needs',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tgbot.businessneeds', verbose_name='Потребности бизнеса'),
        ),
    ]
