# Generated by Django 4.0.6 on 2022-11-08 10:25

from django.db import migrations

def create_business_needs(apps, schema_editor):
    BusinessNeeds = apps.get_model('tgbot', 'BusinessNeeds')
    needs = list()
    NEEDS = [
        "Взаимодействие с представителями власти",
        "Поиск поставщиков и подрядчиков",
        "Поиск клиентов и заказчиков",
        "Участие в тендерах и электронных торгах",
        "Подбор квалифицированных кадров"
    ]
    for need in NEEDS:
        needs.append(
            BusinessNeeds(title=need)
        )
    BusinessNeeds.objects.bulk_create(needs)


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0040_businessneeds_newuser_business_needs_and_more'),
    ]

    operations = [
        migrations.RunPython(create_business_needs),
    ]
