# Generated by Django 4.0.6 on 2022-11-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0041_auto_20221108_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование пользы')),
            ],
            options={
                'verbose_name': 'Польза бизнеса',
                'verbose_name_plural': 'Пользы бизнеса',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='newuser',
            name='business_benefits',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tgbot.businessbenefits', verbose_name='Пользы бизнеса'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_benefits',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tgbot.businessbenefits', verbose_name='Пользы бизнеса'),
        ),
    ]
