# Generated by Django 4.0.6 on 2022-11-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0043_auto_20221108_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbenefits',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Наименование пользы'),
        ),
    ]
