# Generated by Django 4.0.6 on 2022-11-08 14:07

from django.db import migrations

def create_business_benefits(apps, schema_editor):
    BusinessBenefits = apps.get_model('tgbot', 'BusinessBenefits')
    benefits = list()
    BENEFITS = [
        "Делиться связями, компетенциями и ресурсами",
        "Консультировать участников сообщества",
        "Участвовать в мероприятиях Минстроя РФ федерального и регионального уровня",
        "Быть автором экспертных комментариев в профильных СМИ",
        "Предоставлять актуальную для рынка информацию",
        "Предоставлять актуальную аналитику для рынка и СМИ"
    ]

    for benefit in BENEFITS:
        benefits.append(
            BusinessBenefits(title=benefit)
        )
    BusinessBenefits.objects.bulk_create(benefits)


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0044_alter_businessbenefits_title'),
    ]

    operations = [
        migrations.RunPython(create_business_benefits),
    ]
