# Generated by Django 4.0.6 on 2022-11-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0046_businessbranches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbranches',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Наименование отрасли'),
        ),
    ]
