# Generated by Django 4.0.6 on 2022-11-08 14:51

from django.db import migrations

def create_business_branches(apps, schema_editor):
    BusinessBranches = apps.get_model('tgbot', 'BusinessBranches')
    branches = list()
    BRANCHES = [
        "Цифровизация городского хозяйства",
        "IT Технологии",
        "IT Технологии в строительстве и архитектуре",
        "Девелопмент",
        "Группа управления коммерческой недвижимостью",
        "Группа управления жилой недвижимостью",
        "Проектные организации",
        "Строительно-монтажные организации",
        "Производители и поставщики строительных материалов",
        "Строительное оборудование и спецтехника",
        "HR в области строительства",
        "Оценка и экспертная деятельность",
        "Разработка специальных технических условий",
        "Металлургия",
        "Финансовый сектор",
        "Сектор юридических услуг",
        "Кадастровые и геодезические услуги",
        "Благоустройство, ландшафтный дизайн, инфраструктура",
    ]

    for branch in BRANCHES:
        branches.append(
            BusinessBranches(title=branch)
        )
    BusinessBranches.objects.bulk_create(branches)


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0047_alter_businessbranches_title'),
    ]

    operations = [
        migrations.RunPython(create_business_branches),
    ]
