# Generated by Django 4.0.6 on 2022-11-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0048_auto_20221108_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='business_branches',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tgbot.businessbranches', verbose_name='Отрасли бизнеса'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_branches',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tgbot.businessbranches', verbose_name='Отрасли бизнеса'),
        ),
    ]
