# Generated by Django 4.0.6 on 2022-11-10 07:01

from django.db import migrations, models
import tgbot.models.business_branches


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0050_auto_20221109_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessbranches',
            options={'ordering': ['order_number', 'id'], 'verbose_name': 'Отрасль бизнеса', 'verbose_name_plural': 'Отрасли бизнеса'},
        ),
        migrations.AddField(
            model_name='businessbranches',
            name='order_number',
            field=models.IntegerField(default=tgbot.models.business_branches.inc, verbose_name='Порялковый номер в списке'),
        ),
    ]
