# Generated by Django 4.0.6 on 2022-11-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0053_newuser_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessneeds',
            name='admin_aprooved',
            field=models.BooleanField(default=False, verbose_name='Одобрено администратором'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='created_business_needs',
            field=models.ManyToManyField(blank=True, related_name='creators_%(app_label)s_%(class)s_related', related_query_name='creators_%(app_label)s_%(class)ss', to='tgbot.businessneeds', verbose_name='Созданные пользователем потребности бизнеса'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_business_needs',
            field=models.ManyToManyField(blank=True, related_name='creators_%(app_label)s_%(class)s_related', related_query_name='creators_%(app_label)s_%(class)ss', to='tgbot.businessneeds', verbose_name='Созданные пользователем потребности бизнеса'),
        ),
    ]
