# Generated by Django 4.0.6 on 2022-11-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0055_auto_20221112_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbenefits',
            name='admin_aprooved',
            field=models.BooleanField(default=False, verbose_name='Одобрено администратором'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='created_business_benefits',
            field=models.ManyToManyField(blank=True, related_name='creators_%(app_label)s_%(class)s_related', related_query_name='creators_%(app_label)s_%(class)ss', to='tgbot.businessbenefits', verbose_name='Созданные пользователем пользы бизнеса'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_business_benefits',
            field=models.ManyToManyField(blank=True, related_name='creators_%(app_label)s_%(class)s_related', related_query_name='creators_%(app_label)s_%(class)ss', to='tgbot.businessbenefits', verbose_name='Созданные пользователем пользы бизнеса'),
        ),
    ]
