# Generated by Django 4.0.6 on 2022-11-12 14:39

from django.db import migrations

def approve_admin_business_benefits(apps, schema_editor):
    BusinessBenefits = apps.get_model('tgbot', 'BusinessBenefits')
    BENEFITS = [
        "Делиться связями и компетенциями",
        "Консультировать участников сообщества",
        "Быть автором экспертных комментариев",
        "Предоставлять актуальную аналитику",
    ]
    BusinessBenefits.objects.filter(title__in=BENEFITS).update(admin_aprooved=True)

class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0056_businessbenefits_admin_aprooved_and_more'),
    ]

    operations = [
        migrations.RunPython(approve_admin_business_benefits),
    ]
