# Generated by Django 4.0.6 on 2022-11-12 14:55

from django.db import migrations, models
import tgbot.models.business_benefits
import tgbot.models.business_needs


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0057_auto_20221112_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbenefits',
            name='order_number',
            field=models.IntegerField(default=tgbot.models.business_benefits.inc, verbose_name='Порядковый номер в списке'),
        ),
        migrations.AlterField(
            model_name='businessneeds',
            name='order_number',
            field=models.IntegerField(default=tgbot.models.business_needs.inc, verbose_name='Порядковый номер в списке'),
        ),
    ]
