# Generated by Django 4.0.6 on 2022-11-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0059_tggroups_show_for_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='business_club_member',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='Членство в бизнес клубах'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_club_member',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='Членство в бизнес клубах'),
        ),
    ]
