# Generated by Django 4.0.6 on 2022-12-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0060_alter_newuser_business_club_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tggroups',
            name='send_new_users',
            field=models.BooleanField(default=False, verbose_name='Отправлять сообщения о новых пользователях'),
        ),
    ]
