# Generated by Django 4.0.6 on 2022-12-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0061_tggroups_send_new_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tggroups',
            name='send_advertisements',
            field=models.BooleanField(default=False, verbose_name='Отправлять сообщения о рекламных сообщениях'),
        ),
    ]
