# Generated by Django 4.0.6 on 2022-12-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0062_tggroups_send_advertisements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'ordering': ['id', 'user'], 'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AddField(
            model_name='offers',
            name='decision',
            field=models.CharField(choices=[('accepted', 'Принято'), ('rejected', 'Отклонено'), ('under_consideration', 'На рассмотрении')], default='under_consideration', max_length=50, verbose_name='Решение пользователя'),
        ),
        migrations.AddField(
            model_name='offers',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_offers', to='tgbot.user', verbose_name='Инициатор предложения'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='tgbot.user', verbose_name='Пользователь'),
        ),
    ]
