# Generated by Django 4.0.6 on 2022-12-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0063_alter_offers_options_offers_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='create_done',
            field=models.BooleanField(default=False, verbose_name='Создание закончено'),
        ),
        migrations.AddField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
    ]
