# Generated by Django 4.0.6 on 2022-11-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0060_alter_newuser_business_club_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essence', models.CharField(max_length=900, verbose_name='Суть предложения')),
                ('file', models.FileField(blank=True, null=True, upload_to='advertisement_files', verbose_name='Прикрепленный файл')),
                ('file_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='id прикрепленного файла')),
                ('admin_aprooved', models.BooleanField(default=False, verbose_name='Одобрено администратором')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рекламные предложения',
                'verbose_name_plural': 'Рекламное предложение',
                'ordering': ['id'],
            },
        ),
    ]
