# Generated by Django 4.0.6 on 2022-11-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['id'], 'verbose_name': 'Рекламное предложение', 'verbose_name_plural': 'Рекламные предложения'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='essence',
            field=models.TextField(max_length=900, verbose_name='Суть предложения'),
        ),
    ]
