# Generated by Django 4.0.6 on 2022-12-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='file',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='file_id',
        ),
        migrations.CreateModel(
            name='AdvertisementVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(blank=True, null=True, upload_to='advertisement_files', verbose_name='Прикрепленное видео')),
                ('video_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='id прикрепленного видео')),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='advertisement.advertisement', verbose_name='Видео рекламного сообщения')),
            ],
            options={
                'verbose_name': 'Видео рекламного сообщения',
                'verbose_name_plural': 'Видео рекламных сообщений',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisement_files', verbose_name='Прикрепленное изображение')),
                ('image_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='id прикрепленного изображения')),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.advertisement', verbose_name='Изображение рекламного сообщения')),
            ],
            options={
                'verbose_name': 'Изображение рекламного сообщения',
                'verbose_name_plural': 'Изображения рекламных сообщений',
                'ordering': ['id'],
            },
        ),
    ]
