# Generated by Django 4.0.6 on 2022-12-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_remove_advertisement_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='create_done',
            field=models.BooleanField(default=False, verbose_name='Создание закончено'),
        ),
    ]
