# Generated by Django 4.0.6 on 2022-08-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0013_user_verified_by_security_alter_offers_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.IntegerField(default=0, verbose_name='Число сообщений')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.tggroups', verbose_name='Пользователь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщений в группе',
                'verbose_name_plural': 'Статистика сообщений',
                'ordering': ['user', 'group'],
            },
        ),
    ]
