# Generated by Django 4.0.6 on 2022-08-24 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_messagestatistic_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatistic',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
