# Generated by Django 4.0.6 on 2022-08-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='Код типа задания')),
                ('name', models.CharField(max_length=150, verbose_name='Тип задания')),
            ],
            options={
                'verbose_name': 'Тип задания',
                'verbose_name_plural': 'Типы заданий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='Код задания')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя задания')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата запуска')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время запуска')),
                ('mon', models.BooleanField(default=False, verbose_name='пн')),
                ('tue', models.BooleanField(default=False, verbose_name='вт')),
                ('wed', models.BooleanField(default=False, verbose_name='ср')),
                ('thu', models.BooleanField(default=False, verbose_name='чт')),
                ('fri', models.BooleanField(default=False, verbose_name='пт')),
                ('sat', models.BooleanField(default=False, verbose_name='сб')),
                ('san', models.BooleanField(default=False, verbose_name='вс')),
                ('day', models.IntegerField(null=True, verbose_name='День месяца')),
                ('interval', models.IntegerField(null=True, verbose_name='интервал выполнения, сек.')),
                ('is_active', models.BooleanField(default=False, verbose_name='пн')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheduler.tasktypes', verbose_name='Тип задания')),
            ],
            options={
                'verbose_name': 'Тип задания',
                'verbose_name_plural': 'Типы заданий',
                'ordering': ['name'],
            },
        ),
    ]
