# Generated by Django 4.0.6 on 2022-08-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sheduler.tasktypes', verbose_name='Тип задания'),
        ),
    ]
