# Generated by Django 4.0.6 on 2022-08-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0003_alter_tasks_options_alter_tasks_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_type',
        ),
        migrations.DeleteModel(
            name='TaskTypes',
        ),
    ]
