# Generated by Django 4.0.6 on 2022-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0005_messagetemplates_messagestosend'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestosend',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
