# Generated by Django 4.0.6 on 2022-11-08 21:59

from django.db import migrations

def create_business_branches(apps, schema_editor):
    MessageTemplates = apps.get_model('sheduler', 'MessageTemplates')
    MessageTemplates.objects.create(
        code="wait_approve_message",
        name="Шаблон сообщения ожидания одобрения анкеты пользователя",
        text="Ваш профиль отправлен на адмиссию. " \
            "Это может занять некоторое время. Как только заявка будет "\
                "одобрена, мы направим вам уведомление."
    )

class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0006_messagestosend_comment'),
    ]

    operations = [
        migrations.RunPython(create_business_branches),
    ]
