log:
  level: INFO

tls:
  options:
    default:
      minVersion: VersionTLS13

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "urbaniusclub@yandex.ru"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-api-router:
      rule: "Host(`bot.urbanius.club`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      priority: 1
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    web-secure-bot-router:
      rule: "Host(`bot.urbanius.club`) && PathPrefix(`/webhook`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: bot
      priority: 2
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt
    
    media-router:
      rule: "Host(`bot.urbanius.club`) && PathPrefix(`/media`)"
      entryPoints:
        - web-secure
      service: nginx-media
      priority: 2
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    web-secure-api-router-stage:
      rule: "Host(`stage-bot.urbanius.club`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-stage
      priority: 1
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt
    
    media-router-stage:
      rule: "Host(`stage-bot.urbanius.club`) && PathPrefix(`/media`)"
      entryPoints:
        - web-secure
      service: nginx-media-stage
      priority: 2
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:8001

    bot:
      loadBalancer:
        servers:
          - url: http://bot:80

    nginx-media:
      loadBalancer:
        servers:
          - url: http://nginx-media

    django-stage:
      loadBalancer:
        servers:
          - url: http://django-stage:8001

    nginx-media-stage:
      loadBalancer:
        servers:
          - url: http://nginx-media-stage

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
